routes/web.php
<?php

//user controller
Route::group(['namespace'=>'User'],function(){

	Route::get('/','HomeController@index');
	Route::get('/post','HomeController@post');

});







//Admin routes


Route::group(['namespace'=>'Admin'],function(){
	    Route::get('admin/home','HomeController@index');
	    //post routes
		Route::resource('admin/post','PostController');
		//tag routes
		Route::resource('admin/tag','TagController');
		//category routes
		Route::resource('admin/category','CategoryController');
		//User routes
		Route::resource('admin/user','UserController');
	});

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->get();
        return view('admin.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     $request->validate([
            
            'name' => 'required|max:255',
            'slug'=>'required|max:100',
      ]);
        $category=new Category();
        $category->name=$request->name;
        $category->slug=$request->slug;
        $category->save();
        return redirect(route('category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.layout')
@section('content')

    <!-- Content Header (Page header) -->
   

    <!-- Main content -->
    <section class="content" style="margin-left: 5px">
     

          <div  class="container">
          <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Create Category</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('category.store')}}" method="post">
                @csrf
                <div class="card-body">
                  <div class="row">
                  	<div class="col-md-3"></div>
                  	<div class="col-md-offset-3 col-md-6">
                  		<div class="form-group">
                    	<label for="title">Category title</label>
                    	<input type="text" name="name" class="form-control" id="name" placeholder="Category Title">
                  	</div>
                 
                  	<div class="form-group">
                    	<label for="slug">Category Slug</label>
                    	<input type="text" name="slug" class="form-control" id="slug" placeholder="Category slug">
                  	</div>
          
                 
             
              		<div class="form-group">
                  		<button type="submit" class="btn btn-primary">Submit</button>
                      <a href="{{route('category.index')}}" class="btn btn-warning">Back</a>
              		</div>
                  	</div>
                  	

                  </div>
                     
            </div>
             

                <!-- tools box -->
              
             </form>
           
          
              
              
          </div>
          
          
          </div>
        </div>
        <!-- /.col-->
      </div>
  </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  
@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layout')
@section('css')
 <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
@endsection
@section('content')
<div class="card">
            <div class="card-header">
              <div class="row">
              <div class="col-md-5">
                 <h3 class="card-title">Category table</h3>
              </div>
             
              <div class='col-md-offset-5' > <a class='btn btn-success' href="{{route('category.create')}}">Add category</a></div>

             
              </div>
            </div>
	 <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Sl.No</th>
                  <th>Category Name</th>
                  <th>Slug</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                  @foreach($categories as $category)
                <tr>
                  <td>{{$category->id}}</td>
                  <td>{{$category->name}}</td>
                  <td>{{$category->slug}}</td>
                  <td> </td>
                  <td>X</td>
                </tr>
                @endforeach
             
                </tbody>
                <tfoot>
                <tr>
                  <th>Rendering engine</th>
                  <th>Browser</th>
                  <th>Platform(s)</th>
                  <th>Engine version</th>
                  <th>CSS grade</th>
                </tr>
                </tfoot>
              </table>
            </div>
        </div>
  @section('script')
            <script src="{{ asset('admin/plugins/datatables/jquery.dataTables.js') }}"></script>
            <script src="{{ asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
  @endsection
@endsection