routes/web.php
<?php

//user controller
Route::group(['namespace'=>'User'],function(){

	Route::get('/','HomeController@index');
	Route::get('/post','HomeController@post');

});







//Admin routes


Route::group(['namespace'=>'Admin'],function(){
	    Route::get('admin/home','HomeController@index');
	    //post routes
		Route::resource('admin/post','PostController');
		//tag routes
		Route::resource('admin/tag','TagController');
		//category routes
		Route::resource('admin/category','CategoryController');
		//User routes
		Route::resource('admin/user','UserController');
	});

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\post;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $request->validate([
            
            'title' => 'required|max:255',
            'subtitle' => 'required|max:100',
            'slug'=>'required|max:100',
            'body' => 'required|max:1000',
            ]);

        if($request->hasFile('image')){
          $image= $request->file('image'); 
            $image_name=str_random(20);
            $ext=strtolower($image->getClientOriginalExtension());
            $image_full_name=$image_name.'.'.$ext;
            $upload_path='uploads/images/';
            $image_url=$upload_path.$image_full_name; 
            $image->move($upload_path,$image_full_name);            
            //Image::make($image)->resize(300, 300)->save( public_path( $image_url ) );
            $post->image=$image_url;
            
        }
            $post=new post();
            $post->title=$request->title;
            $post->subtitle=$request->subtitle;
            $post->slug=$request->slug;
          //  $post->status=$request->status;
            $post->body=$request->body;
            //$post->image=$request->image;
           /* $post->posted_by=$request->posted_by;
            $post->like=$request->like;
            $post->dislike=$request->dislike;*/
            $post->save();
            return redirect(route('post.index'));


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/PostController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
    //
}

resources/views/admin/post/create.blade.php
@extends('admin.layout')
@section('content')

    <!-- Content Header (Page header) -->
   

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">


          <div class="card card-outline card-info">
            

            <div class="card-header">
              <h3 class="card-title">
                Bootstrap WYSIHTML5
                <small>Simple and fast</small>
              </h3>
            </div>

          <div  class="container">
          <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Create Post</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('post.store')}}" method="post">
                @csrf
                <div class="card-body">
                  <div class="row">
                     <div class="col-md-6">
                     <div class="form-group">
                    <label for="title">Post title</label>
                    <input type="text" name="title" class="form-control" id="title" placeholder="Post Title">
                  </div>
                  <div class="form-group">
                    <label for="title">Post Subtitle</label>
                    <input type="text" name="subtitle" class="form-control" id="subtitle" placeholder="Post subtitle">
                  </div>
                  <div class="form-group">
                    <label for="slug">Post Slug</label>
                    <input type="text" name="slug" class="form-control" id="slug" placeholder="Post slug">
                  </div>
                    

                  </div>
                <div class="col-md-6">
                     <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" name="image" class="custom-file-input" id="image">
                        <label class="custom-file-label" for="image">Choose file</label>
                      </div>
                      <div class="input-group-append">
                        <span class="input-group-text" id="image">Upload</span>
                      </div>
                    </div>
                  </div>
                  <br>
                    <br>


                  <div class="form-check">
                    <input type="checkbox" name="status" class="form-check-input" id="status">
                    <label class="form-check-label"  for="status">Publish</label>
                  </div>
              </div>
                    
                  </div>
                 
                  
                 
                  
                 

              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fas fa-minus"></i></button>
                
              </div>
              
              <div class="mb-3">
                <textarea class="textarea"name="body" placeholder="Place some text here"
                          style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
              </div>
              <p class="text-sm mb-0">
                Editor <a href="https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg">Documentation and license
                information.</a>
              </p>
              

              <div class="form-group">
                  <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
             

                <!-- tools box -->
              
             </form>
           </div>
          
              
              
          </div>
          
          
          </div>
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  
@endsection