routes/web.php
<?php

//user controller
Route::group(['namespace'=>'User'],function(){

	Route::get('/','HomeController@index');
	Route::get('/post','HomeController@post');

});







//Admin routes


Route::group(['namespace'=>'Admin'],function(){
	    Route::get('admin/home','HomeController@index');
	    //post routes
		Route::resource('admin/post','PostController');
		//tag routes
		Route::resource('admin/tag','TagController');
		//category routes
		Route::resource('admin/category','CategoryController');
		//User routes
		Route::resource('admin/user','UserController');
	});

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\tag;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     
        $request->validate([
            
            'name' => 'required|max:255',
            'slug'=>'required|max:100',
            ]);
        $tag=new Tag();
        $tag->name=$request->name;
        $tag->slug=$request->slug;
        $tag->save();
        return redirect(route('tag.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/tag/create.blade.php
@extends('admin.layout')
@section('content')

    <!-- Content Header (Page header) -->
   

    <!-- Main content -->
    <section class="content" style="margin-left: 5px">
     

          <div  class="container">
          <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Create Post</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('tag.store')}}" method="post">
                @csrf
                <div class="card-body">
                  <div class="row">
                  	<div class="col-md-3"></div>
                  	<div class="col-md-offset-3 col-md-6">
                  		<div class="form-group">
                    	<label for="title">Tag title</label>
                    	<input type="text" name="name" class="form-control" id="name" placeholder="Tag Title">
                  	</div>
                 
                  	<div class="form-group">
                    	<label for="slug">Post Slug</label>
                    	<input type="text" name="slug" class="form-control" id="slug" placeholder="Tag slug">
                  	</div>
          
                 
             
              		<div class="form-group">
                  		<button type="submit" class="btn btn-primary">Submit</button>
              		</div>
                  	</div>
                  	

                  </div>
                     
            </div>
             

                <!-- tools box -->
              
             </form>
           
          
              
              
          </div>
          
          
          </div>
        </div>
        <!-- /.col-->
      </div>
  </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  
@endsection